/*
 * Madrush API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// SubscriberApiRouter defines the required methods for binding the api requests to a responses for the SubscriberApi
// The SubscriberApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SubscriberApiServicer to perform the required actions, then write the service results to the http response.
type SubscriberApiRouter interface { 
	CreateSubscriber(http.ResponseWriter, *http.Request)
	ShowSubscriberById(http.ResponseWriter, *http.Request)
}
// SubscribersApiRouter defines the required methods for binding the api requests to a responses for the SubscribersApi
// The SubscribersApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SubscribersApiServicer to perform the required actions, then write the service results to the http response.
type SubscribersApiRouter interface { 
	ListSubscribers(http.ResponseWriter, *http.Request)
}


// SubscriberApiServicer defines the api actions for the SubscriberApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type SubscriberApiServicer interface { 
	CreateSubscriber() (interface{}, error)
	ShowSubscriberById(string) (interface{}, error)
}


// SubscribersApiServicer defines the api actions for the SubscribersApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type SubscribersApiServicer interface { 
	ListSubscribers(int32) (interface{}, error)
}
