/*
 * Madrush API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A SubscriberApiController binds http requests to an api service and writes the service results to the http response
type SubscriberApiController struct {
	service SubscriberApiServicer
}

// NewSubscriberApiController creates a default api controller
func NewSubscriberApiController(s SubscriberApiServicer) Router {
	return &SubscriberApiController{service: s}
}

// Routes returns all of the api route for the SubscriberApiController
func (c *SubscriberApiController) Routes() Routes {
	return Routes{
		{
			"CreateSubscriber",
			strings.ToUpper("Post"),
			"/v1/subscribers",
			c.CreateSubscriber,
		},
		{
			"ShowSubscriberById",
			strings.ToUpper("Get"),
			"/v1/subscriber/{id}",
			c.ShowSubscriberById,
		},
	}
}

// CreateSubscriber - Create a subscriber
func (c *SubscriberApiController) CreateSubscriber(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.CreateSubscriber()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// ShowSubscriberById - Info for a specific subscriber
func (c *SubscriberApiController) ShowSubscriberById(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id := params["id"]
	result, err := c.service.ShowSubscriberById(id)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
