/*
 * Madrush API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// SubscriberApiService is a service that implents the logic for the SubscriberApiServicer
// This service should implement the business logic for every endpoint for the SubscriberApi API. 
// Include any external packages or services that will be required by this service.
type SubscriberApiService struct {
}

// NewSubscriberApiService creates a default api service
func NewSubscriberApiService() SubscriberApiServicer {
	return &SubscriberApiService{}
}

// CreateSubscriber - Create a subscriber
func (s *SubscriberApiService) CreateSubscriber() (interface{}, error) {
	// TODO - update CreateSubscriber with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'CreateSubscriber' not implemented")
}

// ShowSubscriberById - Info for a specific subscriber
func (s *SubscriberApiService) ShowSubscriberById(id string) (interface{}, error) {
	// TODO - update ShowSubscriberById with the required logic for this service method.
	// Add api_subscriber_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ShowSubscriberById' not implemented")
}
