/*
 * Madrush API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// SubscribersApiService is a service that implents the logic for the SubscribersApiServicer
// This service should implement the business logic for every endpoint for the SubscribersApi API. 
// Include any external packages or services that will be required by this service.
type SubscribersApiService struct {
}

// NewSubscribersApiService creates a default api service
func NewSubscribersApiService() SubscribersApiServicer {
	return &SubscribersApiService{}
}

// ListSubscribers - List all subscribers
func (s *SubscribersApiService) ListSubscribers(limit int32) (interface{}, error) {
	// TODO - update ListSubscribers with the required logic for this service method.
	// Add api_subscribers_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ListSubscribers' not implemented")
}
