/*
 * Madrush API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strconv"
	"strings"
)

// A SubscribersApiController binds http requests to an api service and writes the service results to the http response
type SubscribersApiController struct {
	service SubscribersApiServicer
}

// NewSubscribersApiController creates a default api controller
func NewSubscribersApiController(s SubscribersApiServicer) Router {
	return &SubscribersApiController{service: s}
}

// Routes returns all of the api route for the SubscribersApiController
func (c *SubscribersApiController) Routes() Routes {
	return Routes{
		{
			"ListSubscribers",
			strings.ToUpper("Get"),
			"/v1/subscribers",
			c.ListSubscribers,
		},
	}
}

// ListSubscribers - List all subscribers
func (c *SubscribersApiController) ListSubscribers(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	limit, _ := strconv.Atoi(query.Get("limit"))
	result, err := c.service.ListSubscribers(int32(limit))
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
