/*
 * Madrush API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/ennc0d3/madrush/internal/api"
)

func main() {
	log.Printf("Server started")

	SubscriberApiService := openapi.NewSubscriberApiService()
	SubscriberApiController := openapi.NewSubscriberApiController(SubscriberApiService)

	SubscribersApiService := openapi.NewSubscribersApiService()
	SubscribersApiController := openapi.NewSubscribersApiController(SubscribersApiService)

	router := openapi.NewRouter(SubscriberApiController, SubscribersApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
