openapi: "3.0.0"
info:
  version: 1.0.0
  title: Madrush API
  license:
    name: MIT
servers:
  - url: http://madrush.io/v1
paths:
  /subscribers:
    get:
      summary: List all subscribers
      operationId: listSubscribers
      tags:
        - subscribers
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of subscribers
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscribers"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a subscriber
      operationId: createSubscriber
      tags:
        - subscriber
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /subscriber/{id}:
    get:
      summary: Info for a specific subscriber
      operationId: showSubscriberById
      tags:
        - subscriber
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the subscriber to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscriber"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Subscriber:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        subsType:
          $ref: "#/components/schemsas/SubscriptionType"
    Subscribers:
      type: array
      items:
        $ref: "#/components/schemas/Subscriber"
    SubscriptionType:
      required:
        - subsType
      properties:
        subsType:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
